"""add morning split shift fields

Revision ID: 718180c277e0
Revises: b98e387c30d6
Create Date: 2025-10-13 13:07:07.249711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718180c277e0'
down_revision: Union[str, Sequence[str], None] = 'b98e387c30d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('morning_start_time', sa.String(), nullable=True))
    op.add_column('turns', sa.Column('morning_end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'morning_end_time')
    op.drop_column('turns', 'morning_start_time')
    # ### end Alembic commands ###
