"""add split shift fields to Turn

Revision ID: b98e387c30d6
Revises: 37941eafcf87
Create Date: 2025-10-13 12:59:34.275128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98e387c30d6'
down_revision: Union[str, Sequence[str], None] = '37941eafcf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('afternoon_start_time', sa.String(), nullable=True))
    op.add_column('turns', sa.Column('afternoon_end_time', sa.String(), nullable=True))
    op.add_column('turns', sa.Column('days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'days')
    op.drop_column('turns', 'afternoon_end_time')
    op.drop_column('turns', 'afternoon_start_time')
    # ### end Alembic commands ###
