"""add night shift fields to Turn

Revision ID: d9b3c02164b2
Revises: afb88d68ee5a
Create Date: 2025-10-20 07:21:23.067728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b3c02164b2'
down_revision: Union[str, Sequence[str], None] = 'afb88d68ee5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('night_start_time', sa.String(), nullable=True))
    op.add_column('turns', sa.Column('night_end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'night_end_time')
    op.drop_column('turns', 'night_start_time')
    # ### end Alembic commands ###
