"""rename type to shift in turns

Revision ID: f2fcb323a4fd
Revises: 718180c277e0
Create Date: 2025-10-17 10:20:44.084088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fcb323a4fd'
down_revision: Union[str, Sequence[str], None] = '718180c277e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('shift', sa.String(), nullable=True))
    op.drop_column('turns', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('turns', 'shift')
    # ### end Alembic commands ###
